version: "3"

services:

  mariadb:
    build: ./mariadb
    networks:
      - sp7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3305:3306"
    restart: on-failure
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "-uroot"]

  specify7:
    build: ./specify7
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mariadb
    networks:
      - sp7
    volumes:
      - ./specify7/specify6_thick_client:/usr/local/specify6
      - ./specify7/specify7_config:/usr/local/specify_config

  webportal:
    build: ./webportal
    restart: always
    ports:
     - '81:80'
     - '8983:8983'
    tty: true

networks:
  sp7:
    driver: bridge