version: "3"

services:

  mariadb:
    build: ./mariadb
    networks:
      - sp7
    ports:
      - '3307:3306' # uncomment this line if you want to be able to connect to the SQL server from outside the container
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "-uroot"]

  specify7:
    build: ./specify7
    ports:
      - '8080:80'
    depends_on:
      - mariadb
    networks:
      - sp7
    volumes:
      - ./specify7/specify6_thick_client:/usr/local/specify6
      - ./specify7/specify7_config:/usr/local/specify_config

  webportal:
    build: ./webportal
    ports:
      - '80:80'
      - '8983:8983' # comment out this line of you want to restrict access to the Solr admin page
    tty: true

networks:
  sp7:
    driver: bridge